vim.opt.autoindent = true
vim.opt.backspace = "indent,eol,start"
vim.opt.clipboard = "unnamedplus"
vim.opt.completeopt = "menu,menuone,noselect"
-- vim.opt.confirm = true
vim.opt.cursorline = true
-- vim.opt.encoding = "utf-8"
vim.opt.expandtab = true
vim.opt.fileencodings = "utf-8"
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.incsearch = true
-- vim.opt.inccommand = "split"
-- vim.opt.list = true
vim.opt.laststatus = 3
vim.opt.mouse = ""
vim.opt.number = true
vim.opt.pumblend = 20
vim.opt.pumheight = 20
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.shiftround = true
vim.opt.shiftwidth = 4
vim.opt.sidescrolloff = 10
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.timeoutlen = 300 -- lower than the default of 1000 to trigger which-key more quickly
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.updatetime = 250
-- vim.opt.virtualedit = "block"
-- vim.opt.wildmode = "longest:full,full"
vim.opt.wrap = false
